bot:
  prefix: "j."

config:
  buffer_size: 100
  service_pool: 4

guild:
  guild_id: "1416780729127276737"
  member_count_channel_name: "ğŸŒ¸ Ãœyeler â€¢ {count}"
  welcomeMessage: # The embed will be sent when the member joins.
    title: "ğŸŒ¸ LINXUU'ya HoÅŸ Geldin {member.name}"
    description: "{member.mention} aramÄ±za katÄ±ldÄ±!\n\nğŸ“œ KurallarÄ± okumayÄ± unutma, iyi vakit geÃ§ir! ğŸ’–"
    footer: "LINXUU Ailesi Seni Bekliyordu âœ¨"
    banner: "https://media.discordapp.net/attachments/1355878246939361506/1355996244064862509/banner.gif?ex=6948fba9&is=6947aa29&hm=f5b9c41f9d54b7c4ff212c642785e6b42375af44c9963bef7f17e08f8c9fe58c&="
    fields:
      enabled: 1 # True
      number_of_fields: 1 # 2 entries required for 1 field.
      entries:
        - "ğŸ“ Senin SÄ±ran:" # Title
        - "**{count}.Ã¼ye**" # Value
      suggested_channels: 1 # True
      suggested_channels_title: "Ã–nerilen kanallar ğŸ‘‰"
      suggested_channel_list: # The IDs of Suggested Channels
        - "1416780730301677630"
        - "1452224994858893342"


channels:
  general: "1416780730301677630"
  log: "1445060993024659620"
  count: "1432704331798548601"
  about: "1435342197401714880"
  rules: "1452224994858893342"

roles:
  member: "1451621037396725902"